### ISSUE TITLE
slow startup of GTK4 apps

### ISSUE THREAD

**Issue by ad-on-is** [Vladimir-csp/uwsm#87]
I just recently switched to uwsm, using Hyprland.

However, at some point GTK4 apps become very slow to load. I already posted an issue on the hyprlands github, and vaxerski pointed out, this could only be a dbus timeout issue.

https://github.com/hyprwm/Hyprland/issues/9152

Is there anything specific where I should look for, to diagnose this issue?

**Comment by Vladimir-csp** [comment]
Are portals up and running?
```
systemctl --user status xdg-desktop-portal*.service
```

**Comment by ad-on-is** [comment]
They seem to be up and running. I can also do screenshare in the browser, if that's an indication of a working state.
Also, right now, the GTK4 apps start just fine, hence I haven't ran this command in a state where they have the described startup-delay. 

```
» systemctl --user status "xdg-desktop-portal*.service"
● xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Mon 2025-01-27 10:40:25 CET; 1min 2s ago
 Invocation: a332a26e3381435b94ead9eed86a33fc
   Main PID: 5189 (xdg-desktop-por)
      Tasks: 7 (limit: 38235)
        CPU: 82ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal.service
             └─5189 /usr/libexec/xdg-desktop-portal

Jän 27 10:40:25 adonis-PC systemd[3769]: Starting Portal service...
Jän 27 10:40:25 adonis-PC systemd[3769]: Started Portal service.
Jän 27 10:40:25 adonis-PC xdg-desktop-por[5189]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory

● xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
    Drop-In: /run/user/1000/systemd/user/xdg-desktop-portal-gtk.service.d
             └─order-tweak.conf
     Active: active (running) since Mon 2025-01-27 10:40:24 CET; 1min 2s ago
 Invocation: fee8c55dc5034408bc8c93042b59f099
   Main PID: 4466 (xdg-desktop-por)
      Tasks: 5 (limit: 38235)
        CPU: 119ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gtk.service
             └─4466 /usr/libexec/xdg-desktop-portal-gtk

Jän 27 10:40:24 adonis-PC systemd[3769]: Starting Portal service (GTK/GNOME implementation)...
Jän 27 10:40:24 adonis-PC systemd[3769]: Started Portal service (GTK/GNOME implementation).
Jän 27 10:41:10 adonis-PC xdg-desktop-por[4466]: Backend call failed: Cannot invoke method; proxy is for the well-known name org.freedesktop.ScreenSaver without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```

**Comment by RegisHubelia** [comment]
Hi, I'm having the exact same issue.  I ended up trying uwsm with the same behaviour...  After some time, GT4 apps takes for ever to open - restarting portals temporarely fixes the issue.

**Comment by ad-on-is** [comment]
The issue happened again... the desktop-portal services still seem fine

```
systemctl --user status "xdg-desktop-portal*.service"
● xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
    Drop-In: /run/user/1000/systemd/user/xdg-desktop-portal-gtk.service.d
             └─order-tweak.conf
     Active: active (running) since Mon 2025-02-03 10:55:55 CET; 3h 16min ago
 Invocation: 7bf8be24723343d3a9c34c01543cc07a
   Main PID: 428977 (xdg-desktop-por)
      Tasks: 5 (limit: 38205)
        CPU: 194ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gtk.service
             └─428977 /usr/libexec/xdg-desktop-portal-gtk

Feb 03 10:55:55 adonis-PC systemd[3770]: Starting Portal service (GTK/GNOME implementation)...
Feb 03 10:55:55 adonis-PC systemd[3770]: Started Portal service (GTK/GNOME implementation).

● xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Mon 2025-02-03 07:06:52 CET; 7h ago
 Invocation: 738d9158c38a4658949025f3298007d6
   Main PID: 27723 (xdg-desktop-por)
      Tasks: 7 (limit: 38205)
        CPU: 16.728s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal.service
             └─27723 /usr/libexec/xdg-desktop-portal
```

Attempting to restart xdg-desktop-portal results in the following error

```
Feb 03 07:33:12 adonis-PC xdg-desktop-por[27723]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory
Feb 03 07:48:33 adonis-PC xdg-desktop-por[27723]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory
Feb 03 07:50:20 adonis-PC xdg-desktop-por[27723]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory
Feb 03 07:50:33 adonis-PC xdg-desktop-por[27723]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory
Feb 03 07:51:55 adonis-PC xdg-desktop-por[27723]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory
Feb 03 07:52:00 adonis-PC xdg-desktop-por[27723]: Realtime error: Could not get pidns: Could not fstatat ns/pid: Not a directory
Feb 03 08:26:55 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 08:26:55 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 10:35:11 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 10:43:14 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 10:43:37 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 10:45:10 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 10:45:17 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 10:55:46 adonis-PC xdg-desktop-por[27723]: Backend call failed: Remote peer disconnected
Feb 03 14:09:42 adonis-PC xdg-desktop-por[27723]: Failed to ReadAll() from Settings implementation: Timeout was reached
Feb 03 14:12:32 adonis-PC systemd[3770]: xdg-desktop-portal.service: Consumed 16.752s CPU time
```

**Comment by ad-on-is** [comment]
I've disabled it from the execs and will keep an eye whether this still occurs or not.

**Comment by ad-on-is** [comment]
Welp... it happend again, despite not having the nuclear start script executing on launch.

@RegisHubelia Would you mind sharing, how exactly you restart the portals... I tried doing the same, but without success.

**Comment by RegisHubelia** [comment]
I stop hyprland portal then gtk, then base portal.  Then I start hyprland and gtk.  I changed gtk for wlr, not ideal for gtk4 apps but at least it doesn't hang anymore...  So I ended up removing gtk and installing wlr, until hopefully a fix is merged...

**Comment by RegisHubelia** [comment]
Actually - simply restarting gtk portal fixes the issue temporarely...  I'm not really sure this is a uwsm issue - as I tried both with and without with the same behaviour...  IT's really annoying tough...

**Comment by Vladimir-csp** [comment]
I'm going to close this then. Feel free to reopen if you find any connection to uwsm or if any solution is possible on uwsm's side.

**Comment by voytxt** [comment]
Hi @RegisHubelia, sorry to necropost, but did you manage to fix the issue? I have the exact same problem.

**Comment by voytxt** [comment]
That unfortunately didn't solve my problem, but thanks for the reply!
